name: Source Code Check
on:
    push:
        branches:
            - main
            - develop
            - features/**
    pull_request:
        branches:
            - main
            - develop
            - features/**

jobs:
    checks:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                operating-system: [ 'ubuntu-latest']
                php-versions: [  '8.4']
                dependency-stability: [ 'prefer-none' ]

        name: P${{ matrix.php-versions }} - ${{ matrix.operating-system}}

        steps:
            - uses: actions/checkout@v4
            - name: Install PHP versions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, bcmath, soap, intl, iconv, fileinfo
                  coverage: none
            - name: Install Dependencies
              run: composer install --prefer-dist --no-interaction

            - name: Show dir
              run: pwd
            - name: PHP Version
              run: php --version
            - name: Platform check
              run: composer check-platform-reqs
            - name: Security check
              run: composer audit

            # Code quality

            - name: Checking Code styling
              env:
                  PHP_CS_FIXER_IGNORE_ENV: 1
              run: composer run style-check-code

            - name: Static code analysis
              run: composer run static-code

            - name: Rector rules
              run: composer run refactor-check-code





